### ISSUE TITLE
I can´t use this

### ISSUE THREAD

**Issue by Erik-Segoviano** [Cuuuurzel/kivy-material-ui#3]
Hi, I tried download this repo and run setup.py file and demo file but this doesn´t work. Is needed a specific kivy or python versions? (I use python 2.7 and kivy 1.8) Can you tell me suggertions about this problem?

**Comment by curzel-it** [comment]
Hi Erick, this repository hasn't been updated or maintained since the first release a few years ago.
I really am sorry, but I can't provide you any support.

**Comment by Erik-Segoviano** [comment]
too bad!, well, thanks a lot any case.
